// Access token (Bearer). Short-lived (~24h). Auto-refreshed on 401 + via `deno task refresh`.
export const TOKEN =
    "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImExNWQ5OGE2LTdkYzgtNDM3NS05NDk0LTEyOWJlM2RlODVkNCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZSI6ImppbW15aG9wa2luczE2MyIsImVtYSI6ImppbW15aG9wa2luczAwMUBnbWFpbC5jb20iLCJmdWwiOiJqaW1teSBob3BraW5zIiwic2VzIjoiOGRTdTRma1k0QVRwMXY0ayIsImR2YyI6IjU3YzkzNWVmYzA5MGI4ZGY5MDAxYzM0ZmU5ZTgwOTM0IiwidWlkIjo3MjQ5MjQ5LCJjb3UiOiJJRCJ9LCJleHAiOjE3ODA4MTM1NTIsImlhdCI6MTc4MDcyNzE1MiwiaXNzIjoiU1RPQ0tCSVQiLCJqdGkiOiI2NmRkNmVkNy1mNDJiLTQ2NTMtOWYwNS1kMzk2MTViYmQxNjAiLCJuYmYiOjE3ODA3MjcxNTIsInZlciI6InYxIn0.bouBGBdSR3om5iaAMfFGFfqMDiATWGmfDlrUbVeSbyqkhZ8nEIXOC7vdWH15m2-EtYvvCru4ZjLVf8eAvvFuVfML6HhhvcMXG_9u5ysmlIgDPaB8yk6If7Vm4QLD_Bp2LTGSwx8iBuqzAmD9V_cc8QyScHjjSYOuf82GmzCfkbh5YmeKwn3JWopmM-xoCDaglwCUkg_Kx0w7jjWgvQtRASuYaD9RzAtWAM5ebAua663Z79Q3kY4U3IK4pAyfYYlsUuPXQOsJm7AYe0B9yCCoGvHlVARoNO4jNqnn2z-vueoYWYaIwJOs-kSmLUrX_FtflwXsaypAj0KdauvooQwM6g";

// Refresh token (~7d). Used by POST /login/refresh to mint new access tokens.
// SINGLE-USE: each refresh rotates the whole session and invalidates the old pair.
// Source: browser localStorage key `credentialStorage` (URL-decode JSON → state.refresh.token).
export const REFRESH_TOKEN = "PASTE_REFRESH_TOKEN_HERE";
